apiVersion: apps/v1
kind: Deployment
metadata:
  name: soup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soup
  template:
    metadata:
      labels:
        app: soup
        version: v1
    spec:
      containers:
      - name: soup
        image:  novavic/clouddevops_capstone-img-v1:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alphabet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alphabet 
  template:
    metadata:
      labels:
        app: alphabet
        version: v1
    spec:
      containers:
      - name: alphabet
        image:  novavic/clouddevops_capstone-img-v2:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
