# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
spec:
  selector:
    app: soup
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
