# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
spec:
  selector:
    app: soupvsalphabet
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
