# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: alphsoupv1-lb-service
spec:
  selector:
    app: soup
  ports:
    - name: http
      protocol: TCP
      port: 80 # host port/port to be exposed to outside world
      targetPort: 80 #container port
    - name: https
      protocol: TCP
      port: 8443
      targetPort: 443
